version: "3"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
#      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./.nginx/default_location:/etc/nginx/vhost.d/default_location
      - static:/var/www/html/static:ro
    restart: unless-stopped
#  letsencrypt-proxy:
#    image: jrcs/letsencrypt-nginx-proxy-companion
#    container_name: letsencrypt-proxy
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock:ro
#      - letsencrypt-certs:/etc/nginx/certs
#      - letsencrypt-vhost-d:/etc/nginx/vhost.d
#      - letsencrypt-html:/usr/share/nginx/html
#    environment:
#      - DEFAULT_EMAIL=${DJANGO_SUPERUSER_EMAIL}
#      - NGINX_PROXY_CONTAINER=nginx-proxy
#    recstart: unless-stopped
  web:
    build: .
    container_name: masto-mail-blocker
    environment:
      - VIRTUAL_HOST=${HOST}
      - VIRTUAL_PROTO=uwsgi
#      - LETSENCRYPT_HOST=${HOST}
#      - LETSENCRYPT_EMAIL=p${DJANGO_SUPERUSER_EMAIL}
    env_file:
      - .env.example
    expose:
      - 3031
    volumes:
      - uwsgi_data:/tmp/uwsgi/
      - static:/code/staticfiles
    command: >
      sh -c "python manage.py migrate &&
        python manage.py createsuperuser --noinput &&
        python manage.py createcachetable &&
        python manage.py import_domains &&
        python manage.py loaddata app/fixtures/db.json
        python manage.py collectstatic --noinput &&
        python manage.py generate_schedules &&
        uwsgi --ini /code/uwsgi.docker.ini &&
        python manage.py qcluster"

volumes:
  static: