# Generated by Django 4.2.10 on 2024-02-17 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_client_client_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='client_code',
        ),
        migrations.AddField(
            model_name='client',
            name='access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='scope',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
