# Generated by Django 4.2.10 on 2024-02-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_faq_alter_domain_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='access_token',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
